### PR TITLE
RELEASE 2.0.0-alpha1

### PR DESCRIPTION
**Pull request by paulmelnikow**
I'd like to start using some of the features we've been working on!

I feel like we can keep developing toward 2.0, and issue alphas periodically. How does that sound?

### CODE REVIEW

**Comment by paulmelnikow** [comment]
@Fishbowler Let me know if you have thoughts! I'll merge this tonight.

**Comment by Fishbowler** [comment]
Absolutely fine with this!
Do we need to do anything to make it "not the default" when someone does
"npm install icedfrisby"?

**Comment by paulmelnikow** [comment]
Hmm, good question. I thought just putting a prerelease tag was enough, [though now I am not sure](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420). It does look like this should be `2.0.0-alpha.1` so I will change that, to start with.

**Comment by paulmelnikow** [comment]
Looks like it's just a matter of [using a different tag](https://docs.npmjs.com/cli/publish). `npm publish` publishes, and `npm install` installs `latest` by default, so something like `npm publish --tag next` should create a release that won't be upgraded to by default.

**Comment by paulmelnikow** [comment]
I realized this needs a changelog, so I added one.

**Comment by Fishbowler** [comment]
Love it. Let's get this out.

**Pull request merged**
